#include "PhysicsAsset.h"

#include "Object/FUObjectArray.h"
#include "PhysicsBodySetup.h"
#include "Serialization/Archive.h"

#include <algorithm>
#include <cmath>

namespace
{
	constexpr float Pi = 3.14159265358979323846f;
	const FVector PhysicsAssetCapsuleAxis = FVector::ForwardVector;

	FQuat MakeAxisAlignmentQuat(const FVector& FromAxis, const FVector& ToAxis)
	{
		FVector SafeFromAxis = FromAxis;
		FVector SafeToAxis = ToAxis;
		if (SafeFromAxis.IsNearlyZero() || SafeToAxis.IsNearlyZero())
		{
			return FQuat::Identity;
		}

		SafeFromAxis.Normalize();
		SafeToAxis.Normalize();

		const float AxisDot = std::clamp(SafeFromAxis.Dot(SafeToAxis), -1.0f, 1.0f);
		if (AxisDot >= 1.0f - 1.0e-4f)
		{
			return FQuat::Identity;
		}

		if (AxisDot <= -1.0f + 1.0e-4f)
		{
			FVector RotationAxis = SafeFromAxis.Cross(FVector::ForwardVector);
			if (RotationAxis.IsNearlyZero())
			{
				RotationAxis = SafeFromAxis.Cross(FVector::RightVector);
			}
			if (RotationAxis.IsNearlyZero())
			{
				RotationAxis = SafeFromAxis.Cross(FVector::UpVector);
			}

			RotationAxis.Normalize();
			return FQuat::FromAxisAngle(RotationAxis, Pi);
		}

		const FVector RotationAxis = SafeFromAxis.Cross(SafeToAxis);
		FQuat Result(RotationAxis.X, RotationAxis.Y, RotationAxis.Z, 1.0f + AxisDot);
		Result.Normalize();
		return Result;
	}

	bool IsNearlyIdentityQuat(const FQuat& Quat, float Tolerance = 1.0e-3f)
	{
		FQuat SafeQuat = Quat;
		SafeQuat.Normalize();
		return std::fabs(SafeQuat.X) <= Tolerance
			&& std::fabs(SafeQuat.Y) <= Tolerance
			&& std::fabs(SafeQuat.Z) <= Tolerance
			&& std::fabs(std::fabs(SafeQuat.W) - 1.0f) <= Tolerance;
	}

	void RepairAutoGeneratedCapsuleRotations(UPhysicsAsset* PhysicsAsset)
	{
		if (!PhysicsAsset)
		{
			return;
		}

		for (UPhysicsBodySetup* BodySetup : PhysicsAsset->GetMutableBodySetups())
		{
			if (!BodySetup)
			{
				continue;
			}

			for (FPhysicsCapsuleShapeSetup& CapsuleShape : BodySetup->GetMutableShapeSetup().CapsuleShapeSetups)
			{
				if (!IsNearlyIdentityQuat(CapsuleShape.LocalTransform.Rotation)
					|| CapsuleShape.LocalTransform.Location.IsNearlyZero())
				{
					continue;
				}

				CapsuleShape.LocalTransform.Rotation = MakeAxisAlignmentQuat(
					PhysicsAssetCapsuleAxis,
					CapsuleShape.LocalTransform.Location.Normalized());
			}
		}
	}
}

void UPhysicsAsset::Serialize(FArchive& Ar)
{
    constexpr uint32 PhysicsAssetVersionTag = 0x50485953u;
    constexpr uint32 PhysicsAssetVersion = 4u;

    uint32 BodySetupCount = 0u;
    uint32 AssetVersion = PhysicsAssetVersion;
    if (Ar.IsSaving())
    {
        uint32 VersionTag = PhysicsAssetVersionTag;
        uint32 Version = AssetVersion;
        BodySetupCount = static_cast<uint32>(BodySetups.size());

        Ar << VersionTag;
        Ar << Version;
        Ar << PreviewSkeletalMeshPath;
        Ar << GraphViewState;
    }
    else
    {
        uint32 HeaderValue = 0u;
        Ar << HeaderValue;

        if (HeaderValue == PhysicsAssetVersionTag)
        {
            Ar << AssetVersion;
            if (AssetVersion >= 1u)
            {
                Ar << PreviewSkeletalMeshPath;
            }
            else
            {
                PreviewSkeletalMeshPath.clear();
            }

            if (AssetVersion >= 2u)
            {
                Ar << GraphViewState;
            }
            else
            {
                GraphViewState = FPhysicsAssetGraphViewState();
            }

            Ar << BodySetupCount;
        }
        else
        {
            AssetVersion = 0u;
            PreviewSkeletalMeshPath.clear();
            GraphViewState = FPhysicsAssetGraphViewState();
            BodySetupCount = HeaderValue;
        }
    }

    if (Ar.IsSaving())
    {
        Ar << BodySetupCount;
    }

    if (Ar.IsLoading())
    {
        BodySetups.clear();
        BodySetups.reserve(BodySetupCount);
    }

    for (uint32 BodySetupIndex = 0; BodySetupIndex < BodySetupCount; ++BodySetupIndex)
    {
        bool bHasBodySetup = Ar.IsSaving()
            ? (BodySetups[BodySetupIndex] != nullptr)
            : false;
        Ar << bHasBodySetup;

        if (!bHasBodySetup)
        {
            if (Ar.IsLoading())
            {
                BodySetups.push_back(nullptr);
            }
            continue;
        }

        UPhysicsBodySetup* BodySetup = nullptr;
        if (Ar.IsSaving())
        {
            BodySetup = BodySetups[BodySetupIndex];
        }
        else
        {
            BodySetup = GUObjectArray.CreateObject<UPhysicsBodySetup>(this);
        }

        if (BodySetup)
        {
            BodySetup->Serialize(Ar);
        }

        if (Ar.IsLoading())
        {
            BodySetups.push_back(BodySetup);
        }
    }

    Ar << ConstraintSetups;

    if (Ar.IsLoading() && AssetVersion < 4u)
    {
        RepairAutoGeneratedCapsuleRotations(this);
    }
}
