#include "PhysicsAsset.h"

#include "Object/FUObjectArray.h"
#include "PhysicsBodySetup.h"
#include "Serialization/Archive.h"

#include <algorithm>
#include <cmath>

namespace
{
	constexpr float Pi = 3.14159265358979323846f;
	const FVector PhysicsAssetCapsuleAxis = FVector::ForwardVector;

	FQuat MakeAxisAlignmentQuat(const FVector& FromAxis, const FVector& ToAxis)
	{
		FVector SafeFromAxis = FromAxis;
		FVector SafeToAxis = ToAxis;
		if (SafeFromAxis.IsNearlyZero() || SafeToAxis.IsNearlyZero())
		{
			return FQuat::Identity;
		}

		SafeFromAxis.Normalize();
		SafeToAxis.Normalize();

		const float AxisDot = std::clamp(SafeFromAxis.Dot(SafeToAxis), -1.0f, 1.0f);
		if (AxisDot >= 1.0f - 1.0e-4f)
		{
			return FQuat::Identity;
		}

		if (AxisDot <= -1.0f + 1.0e-4f)
		{
			FVector RotationAxis = SafeFromAxis.Cross(FVector::ForwardVector);
			if (RotationAxis.IsNearlyZero())
			{
				RotationAxis = SafeFromAxis.Cross(FVector::RightVector);
			}
			if (RotationAxis.IsNearlyZero())
			{
				RotationAxis = SafeFromAxis.Cross(FVector::UpVector);
			}

			RotationAxis.Normalize();
			return FQuat::FromAxisAngle(RotationAxis, Pi);
		}

		const FVector RotationAxis = SafeFromAxis.Cross(SafeToAxis);
		FQuat Result(RotationAxis.X, RotationAxis.Y, RotationAxis.Z, 1.0f + AxisDot);
		Result.Normalize();
		return Result;
	}

	bool IsNearlyIdentityQuat(const FQuat& Quat, float Tolerance = 1.0e-3f)
	{
		FQuat SafeQuat = Quat;
		SafeQuat.Normalize();
		return std::fabs(SafeQuat.X) <= Tolerance
			&& std::fabs(SafeQuat.Y) <= Tolerance
			&& std::fabs(SafeQuat.Z) <= Tolerance
			&& std::fabs(std::fabs(SafeQuat.W) - 1.0f) <= Tolerance;
	}

	void RepairAutoGeneratedCapsuleRotations(UPhysicsAsset* PhysicsAsset)
	{
		if (!PhysicsAsset)
		{
			return;
		}

		for (UPhysicsBodySetup* BodySetup : PhysicsAsset->GetMutableBodySetups())
		{
			if (!BodySetup)
			{
				continue;
			}

			for (FPhysicsCapsuleShapeSetup& CapsuleShape : BodySetup->GetMutableShapeSetup().CapsuleShapeSetups)
			{
				if (!IsNearlyIdentityQuat(CapsuleShape.LocalTransform.Rotation)
					|| CapsuleShape.LocalTransform.Location.IsNearlyZero())
				{
					continue;
				}

				CapsuleShape.LocalTransform.Rotation = MakeAxisAlignmentQuat(
					PhysicsAssetCapsuleAxis,
					CapsuleShape.LocalTransform.Location.Normalized());
			}
		}
	}

	void LoadLegacySphereShape(FArchive& Ar, FPhysicsSphereShapeSetup& ShapeSetup)
	{
		Ar << ShapeSetup.Name;
		Ar << ShapeSetup.LocalTransform.Location;
		Ar << ShapeSetup.LocalTransform.Rotation;
		Ar << ShapeSetup.LocalTransform.Scale;
		Ar << ShapeSetup.Radius;
		bool bHasPhysicalMaterial = false;
		Ar << bHasPhysicalMaterial;
		ShapeSetup.PhysicalMaterial = nullptr;
		Ar << ShapeSetup.CollisionDesc;
	}

	void LoadLegacyBoxShape(FArchive& Ar, FPhysicsBoxShapeSetup& ShapeSetup)
	{
		Ar << ShapeSetup.Name;
		Ar << ShapeSetup.LocalTransform.Location;
		Ar << ShapeSetup.LocalTransform.Rotation;
		Ar << ShapeSetup.LocalTransform.Scale;
		Ar << ShapeSetup.HalfExtent;
		bool bHasPhysicalMaterial = false;
		Ar << bHasPhysicalMaterial;
		ShapeSetup.PhysicalMaterial = nullptr;
		Ar << ShapeSetup.CollisionDesc;
	}

	void LoadLegacyCapsuleShape(FArchive& Ar, FPhysicsCapsuleShapeSetup& ShapeSetup)
	{
		Ar << ShapeSetup.Name;
		Ar << ShapeSetup.LocalTransform.Location;
		Ar << ShapeSetup.LocalTransform.Rotation;
		Ar << ShapeSetup.LocalTransform.Scale;
		Ar << ShapeSetup.Radius;
		Ar << ShapeSetup.Length;
		bool bHasPhysicalMaterial = false;
		Ar << bHasPhysicalMaterial;
		ShapeSetup.PhysicalMaterial = nullptr;
		Ar << ShapeSetup.CollisionDesc;
	}

	void LoadLegacyConvexShape(FArchive& Ar, FPhysicsConvexShapeSetup& ShapeSetup)
	{
		Ar << ShapeSetup.Name;
		Ar << ShapeSetup.LocalTransform.Location;
		Ar << ShapeSetup.LocalTransform.Rotation;
		Ar << ShapeSetup.LocalTransform.Scale;
		Ar << ShapeSetup.VertexData;
		bool bHasPhysicalMaterial = false;
		Ar << bHasPhysicalMaterial;
		ShapeSetup.PhysicalMaterial = nullptr;
		Ar << ShapeSetup.CollisionDesc;
	}

	void LoadLegacyAggregateShapeSetup(FArchive& Ar, FPhysicsAggregateShapeSetup& ShapeSetup)
	{
		uint32 SphereCount = 0u;
		Ar << SphereCount;
		ShapeSetup.SphereShapeSetups.resize(SphereCount);
		for (FPhysicsSphereShapeSetup& Shape : ShapeSetup.SphereShapeSetups)
		{
			LoadLegacySphereShape(Ar, Shape);
		}

		uint32 BoxCount = 0u;
		Ar << BoxCount;
		ShapeSetup.BoxShapeSetups.resize(BoxCount);
		for (FPhysicsBoxShapeSetup& Shape : ShapeSetup.BoxShapeSetups)
		{
			LoadLegacyBoxShape(Ar, Shape);
		}

		uint32 CapsuleCount = 0u;
		Ar << CapsuleCount;
		ShapeSetup.CapsuleShapeSetups.resize(CapsuleCount);
		for (FPhysicsCapsuleShapeSetup& Shape : ShapeSetup.CapsuleShapeSetups)
		{
			LoadLegacyCapsuleShape(Ar, Shape);
		}

		uint32 ConvexCount = 0u;
		Ar << ConvexCount;
		ShapeSetup.ConvexShapeSetups.resize(ConvexCount);
		for (FPhysicsConvexShapeSetup& Shape : ShapeSetup.ConvexShapeSetups)
		{
			LoadLegacyConvexShape(Ar, Shape);
		}
	}

	void LoadLegacyBodySetup(FArchive& Ar, UPhysicsBodySetup* BodySetup)
	{
		if (!BodySetup)
		{
			return;
		}

		FName TargetBoneName;
		FPhysicsAggregateShapeSetup ShapeSetup;
		uint8 SerializedBodyType = 0u;
		float Mass = 1.0f;
		float LinearDamping = 0.0f;
		float AngularDamping = 0.05f;
		FPhysicsCollisionDesc CollisionDesc;

		Ar << TargetBoneName;
		LoadLegacyAggregateShapeSetup(Ar, ShapeSetup);
		Ar << SerializedBodyType;
		Ar << Mass;
		Ar << LinearDamping;
		Ar << AngularDamping;
		Ar << CollisionDesc;

		BodySetup->SetTargetBoneName(TargetBoneName);
		BodySetup->SetShapeSetup(ShapeSetup);
		BodySetup->SetBodyType(static_cast<EPhysicsBodyType>(SerializedBodyType));
		BodySetup->SetMass(Mass);
		BodySetup->SetLinearDamping(LinearDamping);
		BodySetup->SetAngularDamping(AngularDamping);
		BodySetup->SetCollisionDesc(CollisionDesc);
	}

	void LoadLegacyConstraintSetup(FArchive& Ar, FPhysicsConstraintSetup& ConstraintSetup)
	{
		Ar << ConstraintSetup.ConstraintName;
		Ar << ConstraintSetup.ParentBoneName;
		Ar << ConstraintSetup.ChildBoneName;

		uint8 JointType = static_cast<uint8>(ConstraintSetup.JointType);
		Ar << JointType;
		ConstraintSetup.JointType = static_cast<EPhysicsJointType>(JointType);

		Ar << ConstraintSetup.ParentLocalFrame.Location;
		Ar << ConstraintSetup.ParentLocalFrame.Rotation;
		Ar << ConstraintSetup.ParentLocalFrame.Scale;
		Ar << ConstraintSetup.ChildLocalFrame.Location;
		Ar << ConstraintSetup.ChildLocalFrame.Rotation;
		Ar << ConstraintSetup.ChildLocalFrame.Scale;

		Ar << ConstraintSetup.LinearLimit;
		Ar << ConstraintSetup.AngularLimit;
		Ar << ConstraintSetup.TwistLimitMin;
		Ar << ConstraintSetup.TwistLimitMax;
		Ar << ConstraintSetup.SwingLimitY;
		Ar << ConstraintSetup.SwingLimitZ;
		Ar << ConstraintSetup.bDisableCollision;
		Ar << ConstraintSetup.Stiffness;
		Ar << ConstraintSetup.Damping;

		ConstraintSetup.XMotion = ConstraintSetup.LinearLimit > 0.0f ? EPhysicsConstraintMotionMode::Limited : EPhysicsConstraintMotionMode::Locked;
		ConstraintSetup.YMotion = ConstraintSetup.XMotion;
		ConstraintSetup.ZMotion = ConstraintSetup.XMotion;
		ConstraintSetup.Swing1Motion = ConstraintSetup.SwingLimitY > 0.0f ? EPhysicsConstraintMotionMode::Limited : EPhysicsConstraintMotionMode::Locked;
		ConstraintSetup.Swing2Motion = ConstraintSetup.SwingLimitZ > 0.0f ? EPhysicsConstraintMotionMode::Limited : EPhysicsConstraintMotionMode::Locked;
		ConstraintSetup.TwistMotion = (ConstraintSetup.TwistLimitMin != 0.0f || ConstraintSetup.TwistLimitMax != 0.0f)
			? EPhysicsConstraintMotionMode::Limited
			: EPhysicsConstraintMotionMode::Locked;
	}
}

void UPhysicsAsset::Serialize(FArchive& Ar)
{
    constexpr uint32 PhysicsAssetVersionTag = 0x50485953u;
    constexpr uint32 PhysicsAssetVersion = 6u;

    uint32 BodySetupCount = 0u;
    uint32 AssetVersion = PhysicsAssetVersion;
    if (Ar.IsSaving())
    {
        uint32 VersionTag = PhysicsAssetVersionTag;
        uint32 Version = AssetVersion;
        BodySetupCount = static_cast<uint32>(BodySetups.size());

        Ar << VersionTag;
        Ar << Version;
        Ar << PreviewSkeletalMeshPath;
        Ar << GraphViewState;
        uint8 SerializedRagdollMode = static_cast<uint8>(RagdollMode);
        Ar << SerializedRagdollMode;
    }
    else
    {
        uint32 HeaderValue = 0u;
        Ar << HeaderValue;

        if (HeaderValue == PhysicsAssetVersionTag)
        {
            Ar << AssetVersion;
            if (AssetVersion >= 1u)
            {
                Ar << PreviewSkeletalMeshPath;
            }
            else
            {
                PreviewSkeletalMeshPath.clear();
            }

            if (AssetVersion >= 2u)
            {
                Ar << GraphViewState;
            }
            else
            {
                GraphViewState = FPhysicsAssetGraphViewState();
            }

            if (AssetVersion >= 6u)
            {
                uint8 SerializedRagdollMode = 0u;
                Ar << SerializedRagdollMode;
                RagdollMode = static_cast<EPhysicsAssetRagdollMode>(SerializedRagdollMode);
            }
            else
            {
                RagdollMode = EPhysicsAssetRagdollMode::PerBody;
            }

            Ar << BodySetupCount;
        }
        else
        {
            AssetVersion = 0u;
            PreviewSkeletalMeshPath.clear();
            GraphViewState = FPhysicsAssetGraphViewState();
            RagdollMode = EPhysicsAssetRagdollMode::PerBody;
            BodySetupCount = HeaderValue;
        }
    }

    if (Ar.IsSaving())
    {
        Ar << BodySetupCount;
    }

    if (Ar.IsLoading())
    {
        BodySetups.clear();
        BodySetups.reserve(BodySetupCount);
    }

    for (uint32 BodySetupIndex = 0; BodySetupIndex < BodySetupCount; ++BodySetupIndex)
    {
        bool bHasBodySetup = Ar.IsSaving()
            ? (BodySetups[BodySetupIndex] != nullptr)
            : false;
        Ar << bHasBodySetup;

        if (!bHasBodySetup)
        {
            if (Ar.IsLoading())
            {
                BodySetups.push_back(nullptr);
            }
            continue;
        }

        UPhysicsBodySetup* BodySetup = nullptr;
        if (Ar.IsSaving())
        {
            BodySetup = BodySetups[BodySetupIndex];
        }
        else
        {
            BodySetup = GUObjectArray.CreateObject<UPhysicsBodySetup>(this);
        }

        if (BodySetup)
        {
            if (Ar.IsLoading() && AssetVersion < 5u)
            {
                LoadLegacyBodySetup(Ar, BodySetup);
            }
            else
            {
                BodySetup->Serialize(Ar);
            }
        }

        if (Ar.IsLoading())
        {
            BodySetups.push_back(BodySetup);
        }
    }

    if (Ar.IsLoading() && AssetVersion < 5u)
    {
        uint32 ConstraintCount = 0u;
        Ar << ConstraintCount;
        ConstraintSetups.clear();
        ConstraintSetups.resize(ConstraintCount);
        for (FPhysicsConstraintSetup& ConstraintSetup : ConstraintSetups)
        {
            LoadLegacyConstraintSetup(Ar, ConstraintSetup);
        }
    }
    else
    {
        Ar << ConstraintSetups;
    }

    if (Ar.IsLoading() && AssetVersion < 4u)
    {
        RepairAutoGeneratedCapsuleRotations(this);
    }
}
